import { Store } from "./store.js";

/**
 * Represents the base class for all Reagenz components.
 * All Reagenz components are Web Components.
 */
export declare class Component extends HTMLElement {
	/**
	 * Creates a new instance of the Component.
	 *
	 * @param selectors An array containing the selector functions of the component.
	 */
	constructor(selectors?: Function[]);

	/**
	 * Defines the component and under which tag name it should be available.
	 *
	 * @param tagName The name of the element, how it should be available in HTML. Needs to comply to the Web Components standard.
	 * @param componentClass The class of the component.
	 */
	static define(tagName: string, componentClass: CustomElementConstructor): void;

	/**
	 * Dispatches the action in the injected store.
	 * A shorthand for this.dependencies.store.dispatch.
	 *
	 * @param action The Action object which should be dispatched
	 */
	dispatch(action: { type: string; [key: string]: any }): void;

	/**
	 * Loads the value from the given attribute and tries to convert it to an array.
	 *
	 * @param attributeName The attribute name where the data should be taken from.
	 *
	 * @returns An array if the conversion was successful. If the value can't be converted or the attribute does not exist, null.
	 */
	getArrayAttribute(attributeName: string): any[] | null;

	/**
	 * Loads the value from the given attribute and tries to convert it to a boolean value.
	 *
	 * @param attributeName The attribute name where the data should be taken from.
	 *
	 * @returns true if the value is "true", false if the value is "false", or null if the value cannot be converted.
	 */
	getBooleanAttribute(attributeName: string): boolean | null;

	/**
	 * Loads the value from the given attribute and tries to convert it to a number.
	 *
	 * @param attributeName The attribute name where the data should be taken from.
	 *
	 * @returns A number if the conversion was successful, or null if the value can't be converted.
	 */
	getNumberAttribute(attributeName: string): number | null;

	/**
	 * Loads the value from the given attribute and tries to convert it to a JavaScript object.
	 *
	 * @param attributeName The attribute name where the data should be taken from.
	 *
	 * @returns A JavaScript object if the conversion was successful, or null if the value can't be converted.
	 */
	getObjectAttribute(attributeName: string): Record<string, any> | null;

	/**
	 * Get's executed when the component is added to the DOM.
	 * To prevent errors and memory leaks in Reagenz, use this function instead of connectedCallback.
	 */
	onConnect?(): void;

	/**
	 * Get's executed when the component is removed from the DOM.
	 * To prevent errors and memory leaks in Reagenz, use this function instead of disconnectedCallback.
	 */
	onDisconnect?(): void;

	/**
	 * The HTML of the component is generated by this function.
	 *
	 * @param selectorData The result of the selector functions, which were passed to the constructor.
	 */
	render(selectorData: any[]): string;

	/**
	 * The CSS returned by this function will be added automatically to a style-tag inside the component.
	 * Note that the CSS defined in this function will NOT be scoped, so it can affect any element outside this component too.
	 */
	styles?(): string;

	/**
	 * The dependency container generated by the dependency injection system of Reagenz.
	 * Access all your dependencies via this property.
	 */
	dependencies: {
		store?: Store;
		[key: string]: any;
	};
}
